### ISSUE TITLE
500 error when visiting /stats

### ISSUE THREAD

**Issue by Jamesllllllllll** [stolinski/svelte-5-drizzle-sveltekit-2-example#24]
Hey Scott,

I get a 500 / internal error when I do this:

1. Add a new habit
2. Do not interact with the new habit
3. Click Stats to visit /stats

If I interact with the newly created habit (like click a day to track) then /stats will work.

https://github.com/stolinski/habit-path/assets/125431058/8ffd2ac8-91f6-409f-b8ef-43981bdabc6e

**Comment by stolinski** [comment]
Should be fixed.
